language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

env:
  - SYMFONY_VERSION="2.1"
  - SYMFONY_VERSION="2.*"
  - SYMFONY_VERSION="3.0"
  - SYMFONY_VERSION="3.*"

before_script:
  - composer self-update
  - composer --version
  - composer require symfony/http-foundation:${SYMFONY_VERSION} --no-update

script: composer install -n --dev --prefer-source
